import type { Config } from "tailwindcss";
// Registry animation utilities (theme.extend.animation map). Generated by
// scripts/registry/fetch-magicui.ts. Provides class names like
// `animate-marquee`, `animate-orbit`, `animate-shine` that the registry
// components reference. Pruner does not touch this file - it stays in
// the starter so the build picks up the utilities regardless of which
// components survive pruning.
import registryAnimations from "./components/registry/_meta/tailwind-extension.json";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      animation: { ...registryAnimations.animation },
      // shadcn-style paired colour tokens. Every `bg-<name>` has a matching
      // `text-<name>-foreground`, so the contrast pair is always reachable
      // via class names. Source values live as CSS variables in
      // app/globals.css - override the variables, not these mappings.
      // Tokens are wrapped with `hsl(var(--x) / <alpha-value>)` so Tailwind
      // opacity modifiers like `bg-primary/80` or `text-muted-foreground/70`
      // compile correctly. The CSS variables in globals.css MUST stay in
      // HSL tuple form (e.g. `0 0% 93%`) - a hex value would break the
      // wrapper.
      colors: {
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      // Font roles map to CSS variables set by lib/fonts.ts via app/layout.tsx.
      // - font-body / font-sans: prose, paragraphs, form labels
      // - font-display: hero headlines, section titles, marketing copy
      // - font-mono: code, numerals, version tags, technical accents
      // Agents reach for these via Tailwind utilities; the active pairing
      // (selected in planner.spec.font_pairing) decides which family
      // backs each role. NEVER import next/font/google directly in agent
      // output — use lib/fonts.ts as the single source of truth.
      fontFamily: {
        sans: ["var(--font-body)", "ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
        body: ["var(--font-body)", "ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
        display: ["var(--font-display)", "ui-serif", "Georgia", "serif"],
        mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
